package(default_visibility = ['//visibility:public'])
licenses(['notice'])

java_library(
  name = 'pprof',
  deps = [
    '//third_party/java/guava',
    '//third_party/java/servlet-api',
    #'3rdparty/jvm/com/twitter:util-core',
    #'3rdparty/jvm/com/twitter:util-jvm',
    '//third_party/java/twitter-commons/src/java/com/twitter/common/net/http/handlers:params',
    '//third_party/java/twitter-commons/src/java/com/twitter/common/quantity',
  ],
  srcs = glob(['*.java'])
)
