package(default_visibility = ['//visibility:public'])
licenses(['notice'])

java_library(
  name = 'templating',
  deps = [
    '//third_party/java/guava',
    '//third_party/java/stringtemplate',
    '//third_party/java/twitter-commons/src/java/com/twitter/common/base',
  ],
  srcs = glob(['*.java'])
)
